services:

  api:
        hostname: fastapi
        container_name: fastapi
        build:
            context: ./api
        environment:
            FASTAPI_KEY: ${FASTAPI_KEY}
            FASTAPI_DEBUG: ${FASTAPI_DEBUG}
            MONGODB_DSN: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:27017/${MONGODB_DB}"
            MONGODB_DB: ${MONGODB_DB}
        command: uvicorn main:app --host 0.0.0.0
        ports:
            - "8000:8000"
        restart: always
        depends_on:
            - mongo
        networks:
            - apps_network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./init-mongo:/docker-entrypoint-initdb.d
    networks:
      - apps_network

volumes:
    psql-data:


networks:
    apps_network:
        driver: bridge